{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    app: grafana
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: grafana
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.2.0
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: {{ .Values.grafana.adminUser }}
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: {{ .Values.grafana.adminPassword }}
        - name: GF_SERVER_ROOT_URL
          value: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        resources:
          {{- toYaml .Values.grafana.resources | nindent 10 }}
        volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
        - name: datasource
          mountPath: /etc/grafana/provisioning/datasources
        - name: dashboard-provider
          mountPath: /etc/grafana/provisioning/dashboards
        - name: dashboard
          mountPath: /etc/grafana/provisioning/dashboards/creation-dashboard.json
          subPath: creation-dashboard.json
      volumes:
      - name: storage
        {{- if .Values.grafana.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-grafana-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: datasource
        configMap:
          name: {{ .Release.Name }}-grafana-datasource
      - name: dashboard-provider
        configMap:
          name: {{ .Release.Name }}-grafana-dashboard-provider
      - name: dashboard
        configMap:
          name: {{ .Release.Name }}-grafana-dashboard
{{- end }}